### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by theboywhocode** [Oysiyl/DataCamp_Solutions_Python#2]
Can you please add the snapshot or related document of instruction related to these projects given on the datacamp. I think that will be really helpful in building the concept and grooming someone's skill as the data scientist.

I am adding an example snap from a free project. 

Thanks a bunch in advance.

![datacamp](https://user-images.githubusercontent.com/32708210/52665849-a7b46b00-2f32-11e9-8bd2-051faf102d31.PNG)

**Comment by dmitriy-kisil** [comment]
Sorry for delay, I miss tab with issues. I understand what you want, but now is too late - without subscription I cannot ever check my completed projects to get data for snap(
